src/BRS/BRS.WebUI/Controllers/DestinationController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using BRS.Core.Models;
using BRS.Data;

namespace BRS.WebUI.Controllers
{
    public class DestinationController : Controller
    {
        private Context db = new Context();

        // GET: Destination
        public ActionResult Index()
        {
            return View(db.Destinations.ToList());
        }

        // GET: Destination/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Destination destination = db.Destinations.Find(id);
            if (destination == null)
            {
                return HttpNotFound();
            }
            return View(destination);
        }

        // GET: Destination/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Destination/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name")] Destination destination)
        {
            if (ModelState.IsValid){
              destination.CreatedDate = destination.ModifiedDate = DateTime.Now;
              destination.Deleted = false;
                db.Destinations.Add(destination);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(destination);
        }

        // GET: Destination/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Destination destination = db.Destinations.Find(id);
            if (destination == null)
            {
                return HttpNotFound();
            }
            return View(destination);
        }

        // POST: Destination/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,CreatedDate,ModifiedDate,Deleted")] Destination destination)
        {
            if (ModelState.IsValid)
            {
                db.Entry(destination).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(destination);
        }

        // GET: Destination/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Destination destination = db.Destinations.Find(id);
            if (destination == null)
            {
                return HttpNotFound();
            }
            return View(destination);
        }

        // POST: Destination/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Destination destination = db.Destinations.Find(id);
            db.Destinations.Remove(destination);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

src/BRS/BRS.WebUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using BRS.Core.Models;
using BRS.Data;
using BRS.Logical.Account;
using BRS.WebUI.Models;

namespace BRS.WebUI.Controllers {
  public class HomeController : Controller {
    private Context db = new Context();

    public ActionResult Index() {
      SearchResultViewModel vmodel = new SearchResultViewModel();
      List<Trip> trips = db.Trips.ToList();
      vmodel.Trips = trips;
      vmodel.DepartureDate = DateTime.Now;
      vmodel.NoPassengers = 1;
      return View(vmodel);
    }

    [HttpPost]
    public ActionResult Index(int originId, int destinationId, DateTime date, int noPassengers) {
      SearchResultViewModel vmodel = new SearchResultViewModel();
      List<Trip> trips = db.Trips.ToList();
      var result = trips.Where(x => x.Route.Pickup.ID == originId && x.Route.DropOff.ID == destinationId).ToList();
      vmodel.Trips = trips;
      vmodel.DepartureDate = date;
      vmodel.NoPassengers = noPassengers;

      if(ModelState.IsValid)
      return RedirectToAction("Index", "Reservation", new {originId = originId, destinationId = originId, date = date, noPassengers = noPassengers});

      return View(vmodel);
    }



    public ActionResult About() {
      ViewBag.Message = "Your application description page.";

      return View();
    }

    public ActionResult Contact() {
      ViewBag.Message = "Your contact page.";

      return View();
    }

    
public ActionResult Admin(){
  if(UserSessionManager.Instance.UserRole != UserSessionManager.Erole.Administrator)
      return RedirectToAction("Index");

      return View();
    }

    public ActionResult DestinationsAutocomplete(string term) {

      var items = db.Destinations.ToList();
      var filteredItems = items.Where(x => x.Name.ToLower().Contains(term.ToLower()));
      return Json(filteredItems, JsonRequestBehavior.AllowGet);
    }
  }


}

src/BRS/BRS.WebUI/Controllers/RouteController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using BRS.Core.Models;
using BRS.Data;
using BRS.WebUI.Models;

namespace BRS.WebUI.Controllers {
  public class RouteController : Controller {
    private Context db = new Context();

    // GET: Route
    public ActionResult Index() {
      return View(db.Routes.ToList());
    }

    // GET: Route/Details/5
    public ActionResult Details(int? id) {
      if (id == null) {
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
      }
      Route route = db.Routes.Find(id);
      if (route == null) {
        return HttpNotFound();
      }
      return View(route);
    }

    // GET: Route/Create
    public ActionResult Create() {
      RouteViewModel vmRoute = new RouteViewModel();
      vmRoute.Destinations = GetDestinations();

      return View(vmRoute);
    }

    // POST: Route/Create
    // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
    // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Create([Bind(Include = "ID,PickUpId,DropOffId")] RouteViewModel model) {
      if (ModelState.IsValid) {
        Route route = new Route();
        route.ID = 0;
        route.Pickup = GetDestination(model.PickUpId);
        route.DropOff = GetDestination(model.DropOffId);
        route.CreatedDate = DateTime.Now;
        route.ModifiedDate = DateTime.Now;
        route.Deleted = false;

        db.Routes.Add(route);
        db.SaveChanges();
        return RedirectToAction("Index");
      }

      model.Destinations = GetDestinations();
      return View(model);
    }

    private Destination GetDestination(int pickUpId) {
      return db.Destinations.First(x => x.ID == pickUpId);
    }

    // GET: Route/Edit/5
    public ActionResult Edit(int? id) {
      if (id == null) {
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
      }
      Route route = db.Routes.Find(id);
      if (route == null) {
        return HttpNotFound();
      }
      return View(route);
    }

    // POST: Route/Edit/5
    // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
    // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Edit([Bind(Include = "ID,CreatedDate,ModifiedDate,Deleted")] Route route) {
      if (ModelState.IsValid) {
        db.Entry(route).State = EntityState.Modified;
        db.SaveChanges();
        return RedirectToAction("Index");
      }
      return View(route);
    }

    // GET: Route/Delete/5
    public ActionResult Delete(int? id) {
      if (id == null) {
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
      }
      Route route = db.Routes.Find(id);
      if (route == null) {
        return HttpNotFound();
      }
      return View(route);
    }

    // POST: Route/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public ActionResult DeleteConfirmed(int id) {
      Route route = db.Routes.Find(id);
      db.Routes.Remove(route);
      db.SaveChanges();
      return RedirectToAction("Index");
    }

    protected override void Dispose(bool disposing) {
      if (disposing) {
        db.Dispose();
      }
      base.Dispose(disposing);
    }

    private IEnumerable<Destination> GetDestinations() {
      return db.Destinations.Select(x => x);
    }
  }
}

src/BRS/BRS.WebUI/Controllers/TripController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using BRS.Core.Models;
using BRS.Data;
using BRS.WebUI.Models;

namespace BRS.WebUI.Controllers {
  public class TripController : Controller {
    private Context db = new Context();
    // GET: Trip
    public ActionResult Index() {
      return View(db.Trips.ToList());
    }

    // GET: Trip/Details/5
    public ActionResult Details(int? id) {
      if (id == null) {
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
      }
      Trip trip = db.Trips.Find(id);
      if (trip == null) {
        return HttpNotFound();
      }
      return View(trip);
    }

    // GET: Trip/Create
    public ActionResult Create() {
      TripViewModel vmRoute = new TripViewModel();
      vmRoute.Routes = db.Routes.ToList();
      vmRoute.Vehicles = db.Vehicles.ToList();

      return View(vmRoute);
    }

    // POST: Trip/Create
    // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
    // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Create([Bind(Include = "ID,DateAvailable,DepartureTime,ArrivalTime,Price,RouteId,VehicleId")] TripViewModel tripVm, int[] dateAvailable) {
      tripVm.Routes = db.Routes.ToList();
      tripVm.Vehicles = db.Vehicles.ToList();

      if (ModelState.IsValid) {
        Trip trip = new Trip {
          ID = 0,
          ArrivalTime = tripVm.ArrivalTime,
          DepartureTime = tripVm.DepartureTime,
          DateAvailable = (byte)dateAvailable.Sum(x => x),
          Route = tripVm.Routes.First(x => x.ID == tripVm.RouteId),
          Vehicle = tripVm.Vehicles.First(x => x.ID == tripVm.VehicleId),
          Price = tripVm.Price,
          CreatedDate = DateTime.Now,
          ModifiedDate = DateTime.Now,
          Deleted = false
        };

        db.Trips.Add(trip);
        db.SaveChanges();
        return RedirectToAction("Index");
      }

      return View(tripVm);
    }

    // GET: Trip/Edit/5
    public ActionResult Edit(int? id) {
      if (id == null) {
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
      }
      Trip trip = db.Trips.Find(id);
      if (trip == null) {
        return HttpNotFound();
      }
      return View(trip);
    }

    // POST: Trip/Edit/5
    // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
    // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Edit([Bind(Include = "ID,DateAvailable,DepartureTime,ArrivalTime,Price,CreatedDate,ModifiedDate,Deleted")] Trip trip) {
      if (ModelState.IsValid) {
        db.Entry(trip).State = EntityState.Modified;
        db.SaveChanges();
        return RedirectToAction("Index");
      }
      return View(trip);
    }

    // GET: Trip/Delete/5
    public ActionResult Delete(int? id) {
      if (id == null) {
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
      }
      Trip trip = db.Trips.Find(id);
      if (trip == null) {
        return HttpNotFound();
      }
      return View(trip);
    }

    // POST: Trip/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public ActionResult DeleteConfirmed(int id) {
      Trip trip = db.Trips.Find(id);
      db.Trips.Remove(trip);
      db.SaveChanges();
      return RedirectToAction("Index");
    }

    protected override void Dispose(bool disposing) {
      if (disposing) {
        db.Dispose();
      }
      base.Dispose(disposing);
    }

    private IEnumerable<Destination> GetDestinations() {
      return db.Destinations.Select(x => x);
    }

  }
}

src/BRS/BRS.WebUI/Controllers/VehicleController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using BRS.Core.Models;
using BRS.Data;

namespace BRS.WebUI.Controllers
{
    public class VehicleController : Controller
    {
        private Context db = new Context();

        // GET: Vehicle
        public ActionResult Index()
        {
            return View(db.Vehicles.ToList());
        }

        // GET: Vehicle/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehicle vehicle = db.Vehicles.Find(id);
            if (vehicle == null)
            {
                return HttpNotFound();
            }
            return View(vehicle);
        }

        // GET: Vehicle/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Vehicle/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,PassengerCapacity,VehicleType,Image,Description,Deleted")] Vehicle vehicle)
        {
            if (ModelState.IsValid)
            {
                vehicle.CreatedDate = DateTime.Now;
                vehicle.ModifiedDate = DateTime.Now;
              
                db.Vehicles.Add(vehicle);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(vehicle);
        }

        // GET: Vehicle/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehicle vehicle = db.Vehicles.Find(id);
            if (vehicle == null)
            {
                return HttpNotFound();
            }
            return View(vehicle);
        }

        // POST: Vehicle/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,PassengerCapacity,VehicleType,Image,Description,CreatedDate,ModifiedDate,Deleted")] Vehicle vehicle)
        {
            if (ModelState.IsValid)
            {
                db.Entry(vehicle).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(vehicle);
        }

        // GET: Vehicle/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehicle vehicle = db.Vehicles.Find(id);
            if (vehicle == null)
            {
                return HttpNotFound();
            }
            return View(vehicle);
        }

        // POST: Vehicle/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Vehicle vehicle = db.Vehicles.Find(id);
            db.Vehicles.Remove(vehicle);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

src/BRS/BRS.WebUI/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

src/BRS/BRS.WebUI/Views/Home/Admin.cshtml
<h2>Administrator Page</h2>

<ul>
  <li>@Html.ActionLink("Destination Maintenance", "Index", "Destination")</li>
  <li>@Html.ActionLink("Route Maintenance", "Index", "Route")</li>
  <li>@Html.ActionLink("Vehicle Maintenance", "Index", "Vehicle")</li>
  <li>@Html.ActionLink("Trip Maintenance", "Index", "Trip")</li>

</ul>

src/BRS/BRS.WebUI/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    Whiteware "White Tecnology"<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    809.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

src/BRS/BRS.WebUI/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="row">

  <div id="sidebar" class="col-sm-4">
    <h3>Where do you want to go?</h3>
    <form method="POST" action="Home/Index">
      <fieldset>
        <div class="form-group">
          <label for="origin">*Origin</label>
          <input type="hidden" id="originId" name="originId">
          <input id="origin" name="origin" type="text" class="form-control" placeholder="Santo Domingo" />
        </div>
        <div class="form-group">
          <label for="destination">*Destination</label>
          <input type="hidden" id="destinationId" name="destinationId">
          <input id="destination" name="destination" type="text" class="form-control" placeholder="Santiago" />
        </div>

        <div class="form-group">
          <label for="date">*Date</label>
          <input id="date" name="date" type="date" class="form-control" />
        </div>

        <div class="form-group">
          <label for="noPassengers">*No. Passengers</label>
          <input id="noPassengers" name="noPassengers" type="number" class="form-control" />
        </div>

      </fieldset>
      <button class="btn btn-danger">Clear</button>
      <button class="btn btn-warning">Search</button>
    </form>
  </div>


  <div class="col-sm-8">
    <h1>Today's Offer</h1>

    <div class="col-sm-4">
      <div class="thumbnail">
        <img src="http://placehold.it/240x200" alt="placeholder"/>
        <div class="caption">
          <h3>Offer 1</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo</p>
        </div>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="thumbnail">
        <img src="http://placehold.it/240x200" alt="placeholder"/>
        <div class="caption">
          <h3>Offer 2</h3>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          </p>
        </div>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="thumbnail">
        <img src="http://placehold.it/240x200" alt="placeholder"/>
        <div class="caption">
          <h3>Offer 3</h3>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          </p>
        </div>
      </div>
    </div>
  </div>

</div>

@section Scripts {
  <script>
    $(document).ready(function () {

      var action = '@Url.Action("DestinationsAutocomplete")';

      var getData = function(request, response) {
        $.getJSON(action, { term: request.term }, function(data) {
          response(
            $.map(data, function(el) {
              return {
                label: el.Name,
                value: el.ID
              }
            }));
        });
      };

      $('#origin').autocomplete({
        minLength: 0,
        source: getData,
        focus: function (event, ui) {
          $("#origin").val(ui.item.label);
          return false;
        },
        select: function (event, ui) {
          $("#origin").val(ui.item.label);
          $("#originId").val(ui.item.value);
          return false;
        }
      });

      $('#destination').autocomplete({
        minLength: 0,
        source: getData,
        focus: function (event, ui) {
          $("#destination").val(ui.item.label);
          return false;
        },
        select: function (event, ui) {
          $("#destination").val(ui.item.label);
          $("#destinationId").val(ui.item.value);
          return false;
        }
      });
    });
  </script>
}